version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: flask-web-app
    container_name: web-app
    ports:
      - "8080:8080"
    env_file:
      - db.env
      - app.env
    depends_on:
      - db
    networks:
      - backend-net


  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    image: "db"
    container_name: "db"
    volumes:
      - db:/data/db
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      db.env
    networks:
      - backend-net


volumes:
  db:

networks:
  backend-net:
    name: backend
    driver: bridge

